### PR TITLE
Quiz

### PR DESCRIPTION
**Pull request by VikingPaul**

### CODE REVIEW

**Comment by zoeames** [comment]
Hey Paul - quiz looks great - you are good to merge! :+1:

**Comment by zoeames** [comment]
The only comment i have is a bit nitpicking - your articles are really close together.  Since there are 3 per row at 30% - aka 90% taken up, you have 10% left for spacing.  instead of tacking that 10% at the end of a row, distribute it a little bit - evenly space those articles so they aren't up against each other.  Similarly don't let text run right up against the edge of  your divs/articles.  put a little padding on the text

**Comment by VikingPaul** [comment]
Fixed the spacing between articles and no text is touching the border

**Comment by JoeShep** [comment]
:+1: Merge it

**Pull request merged**
